# Generated by Django 2.0.5 on 2018-05-19 10:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('description', models.CharField(max_length=512)),
                ('image', models.FilePathField(path='static/events/images')),
                ('event_location', models.CharField(max_length=128)),
                ('event_date', models.DateTimeField(verbose_name='event date published')),
                ('publication_date', models.DateTimeField(verbose_name='post date published')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=48)),
                ('last_name', models.CharField(max_length=48)),
                ('password', models.CharField(max_length=48)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=24)),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.User'),
        ),
    ]
