# Generated by Django 2.0.1 on 2018-05-19 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20180519_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='publication_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='post date published'),
        ),
    ]
